---
title: "3618 project 2"
author: "Spike Wang & Xiaoli Zhu"
date: "11/16/2019"
output: html_document
---
```{r}
loan <- 200000
interest <- 0.03
num_periods <- 10
monthly_rate <- (1 + interest)^(1/12) - 1
payment_size <- (loan*monthly_rate)/(1-(1/(1 + monthly_rate))^(num_periods*12))
num <- num_periods*12

print(payment_size)

```
```{r}
amount[1] <- loan*monthly_rate
for (time in 1:num) {amount[time ] <- payment_size*(1-(1/(1+monthly_rate))^(num-time+1))}
print(amount)
interest_paid <- amount
```
```{r}
amount[1] <- payment_size-loan*monthly_rate
for (time in 2:num) {amount[time ] <- payment_size*(1/(1+monthly_rate))^(num-time+1)}
print(amount)
principal_paid <- amount
```

```{r}
amount[1] <- loan
for (time in 1:num) {amount[time + 1] <- amount[time]-principal_paid[time ]}
print(amount)
outstanding_balance <- amount
```

```{r}
x <- c(interest_paid, principal_paid, outstanding_balance)
rownames <- c(0,1:num)
colnames <- c("interest paid", "principal repaid", "outstanding balance")
dimnames = list(rownames, colnames)
amortization <- matrix(x, nrow = 121, ncol = 3, dimnames=dimnames)
amortization
```

